### PR TITLE
Ruby model dev merge.

### PR DESCRIPTION
**Pull request by Kolaer**

### CODE REVIEW

**Review by s3rius — APPROVED** [review]
Seems good. But please check out issue #22. May be better to close it before merging.

**Comment by Kolaer** [comment]
Added vue support. Fixed #22.

**Comment by s3rius** [comment]
The last commit was to provide full vue support.

**Comment by Kolaer** [comment]
Seems like we also need to rebuild docker image now.

**Comment by Kolaer** [comment]
Hmm, looks like it's complaining about not installed webpack. That's odd, because we have it installed in docker image.

image

**Comment by Kolaer** [comment]
That's beyond my comprehension.

image

**Comment by s3rius** [comment]
Wierd flex, but seems it's ok.

**Pull request merged**
